apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taxly-ingress
  namespace: taxly
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - taxly.ng
        - www.taxly.ng
      secretName: taxly-tls-cert
  rules:
    - host: taxly.ng
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taxly-app-service
                port:
                  number: 80
    - host: www.taxly.ng
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taxly-app-service
                port:
                  number: 80
