apiVersion: v1
kind: Secret
metadata:
  name: taxly-secrets
  namespace: taxly
type: Opaque
stringData:
  # App secrets
  APP_KEY: "base64:SEia9Tv/QtdvwYPSS2+34lKCBynLndBmjBmyN8E5Ysk="

  # Database credentials
  DB_PASSWORD: "WXQ3I0ZuVzRAakxxOSRCeA=="
  MYSQL_ROOT_PASSWORD: "SzkkbvhwMiN2TG5ROEB3Ug=="

  # Mail credentials
  MAIL_USERNAME: "taxly@taxly.ng"
  MAIL_PASSWORD: "QsmwuX4caU2T"

  # FIRS API credentials
  FIRS_API_KEY: "825e368e-f405-4e63-85a9-69ba1802f549"
  FIRS_SECRET_KEY: "tWAVe6TpASb2zyUK78v5PNeG9kq4GBKtT6JTDh8aONXkjg5enLPiqqcaQ1GVwLcZCstzAVFBhhtwNvVnvCtWaFFHenczy6Ozp7OO"
  FIRS_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyU0xpdDRtb1RMbFdjd1A4eEp6RQp3ZTdkRHExdC9kMi9zcXdQTlNVandablFPbklabVh4TXY4QUQxemMxdUErZ3VCc2tpUGdoSXd6ekxWYXJoNk1KCndEdVUxSC95V2FPZE1PTnZOQy9OWERybXB5cE5WUDZyQnV3LzVjSERMdEtoZlJ0YkdFa1JSVVF4MVAxUUJ6REsKVVRpaTRJOXJld29zcVQ4V1dBOE8zRVd5ZHJ5TEg1K3JpVmRUNVBPeU1jcU95YUR2bGRqWG9ZdnBSTHlkcmtDQQpkUWpMdkw0bG00TVNxS05WdGVJR0Y4ZWk4M3Juck5wR3hKTVVGYVMwekt5TzBJZlY0alBCK3ZXN3I1TXdzTjRvCkRnWVR2ME85Q050N3JoNlEvYi9XR3Ewakl3WHJ3c3JIQXE4TXNyUVlGV0JIOHpmejMwOHRWMTlRM1hPTnEyWEMKMHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
  FIRS_CERTIFICATE: "NklBL25zYU9QOGc3TXpRWStobE9WdlBQZlovbFIwM1hkdjlkNGI4UkNzQT0="
